image: "hseeberger/scala-sbt:17.0.2_1.6.2_2.13.8"

stages:
  - test
  - publish

test:
  script:
    sbt scalafmtCheckAll coverage test coverageReport coverageAggregate
  artifacts:
    reports:
      junit:
        - ./*/target/test-reports/*.xml
      cobertura:
        - ./*/target/*/coverage-report/cobertura.xml

publish:
  stage: publish
  script:
    sbt universal:packageBin universal:packageZipTarball
  artifacts:
    paths:
      - lesson4/target/universal/*.zip
