image: "hseeberger/scala-sbt:11.0.11_1.5.4_2.13.6"

stages:
  - test

test:
  script:
    sbt scalafmtCheckAll coverage test coverageReport coverageAggregate
  artifacts:
    reports:
      junit:
        - ./*/target/test-reports/*.xml
      cobertura:
        - ./*/target/*/coverage-report/cobertura.xml
